import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { AppSidebar } from "@/components/application/app-navigation/app-sidebar";
import { Topbar } from "@/components/application/topbar/topbar";
import { RouteProvider } from "@/providers/router-provider";
import { Theme } from "@/providers/theme";
import "@/styles/globals.css";
import { cx } from "@/utils/cx";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Starter kit — Untitled UI",
    description: "Generated by Untitled UI CLI",
};

export const viewport: Viewport = {
    themeColor: "#7f56d9",
    colorScheme: "light dark",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cx(inter.variable, "bg-primary antialiased")}>
                <RouteProvider>
                    <Theme>
                        <div className="flex min-h-dvh">
                            <AppSidebar />
                            <div className="flex min-w-0 flex-1 flex-col">
                                <Topbar />
                                <main className="flex-1">{children}</main>
                            </div>
                        </div>
                    </Theme>
                </RouteProvider>
            </body>
        </html>
    );
}
